remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: " "  # Space instead of empty string
description: " "  # Space instead of empty string
github:
  is_project_page: false
  is_user_page: false
show_downloads: false
